[tool.poetry]
name = "yuta"
version = "0.1.0"
description = ""
authors = ["Yann <iamyanndias@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
